export const ffmpegFileFormats = [
  "3dostr",
  "4xm",
  "8088flex TMV",
  "AAX",
  "AA",
  "ACT Voice",
  "Adobe Filmstrip",
  "AIFF",
  "AMR",
  "AMV",
  "APNG",
  "ASF",
  "AST",
  "AVI",
  "AviSynth",
  "AVR",
  "AVS",
  "Beam Software SIFF",
  "Bethesda Softworks VID",
  "Binary text",
  "Bink",
  "Bitmap Brothers JV",
  "BRP",
  "Brute Force & Ignorance",
  "BFSTM",
  "BRSTM",
  "BW64",
  "BWF",
  "codec2 (raw)",
  "codec2 (.c2 files)",
  "CRI ADX",
  "CRI AIX",
  "CRI HCA",
  "Discworld II BMV",
  "Interplay C93",
  "Delphine Software International CIN",
  "Digital Speech Standard (DSS)",
  "CD+G",
  "Phantom Cine",
  "Commodore CDXL",
  "Core Audio Format",
  "CRC testing format",
  "Creative Voice",
  "CRYO APC",
  "D-Cinema audio",
  "Deluxe Paint Animation",
  "DCSTR",
  "DFA",
  "DirectDraw Surface",
  "DSD Stream File (DSF)",
  "DV video",
  "DXA",
  "Electronic Arts cdata",
  "Electronic Arts Multimedia",
  "Ensoniq Paris Audio File",
  "FFM (FFserver live feed)",
  "Flash (SWF)",
  "Flash 9 (AVM2)",
  "FLI/FLC/FLX animation",
  "Flash Video (FLV)",
  "framecrc testing format",
  "FunCom ISS",
  "G.723.1",
  "G.726",
  "G.729 BIT",
  "G.729 raw",
  "GENH",
  "GIF Animation",
  "GXF",
  "HNM",
  "iCEDraw File",
  "ICO",
  "id Quake II CIN video",
  "id RoQ",
  "IEC61937 encapsulation",
  "IFF",
  "IFV",
  "iLBC",
  "Interplay MVE",
  "Iterated Systems ClearVideo",
  "IV8",
  "IVF (On2)",
  "Internet Video Recording",
  "IRCAM",
  "LAF",
  "LATM",
  "LMLM4",
  "LOAS",
  "LRC",
  "LVF",
  "LXF",
  "Magic Lantern Video (MLV)",
  "Matroska",
  "Matroska audio",
  "FFmpeg metadata",
  "MAXIS XA",
  "MCA",
  "MD Studio",
  "Metal Gear Solid: The Twin Snakes",
  "Megalux Frame",
  "MobiClip MODS",
  "MobiClip MOFLEX",
  "Mobotix .mxg",
  "Monkey’s Audio",
  "Motion Pixels MVI",
  "MOV/QuickTime/MP4",
  "MP2",
  "MP3",
  "MPEG-1 System",
  "MPEG-PS (program stream)",
  "MPEG-TS (transport stream)",
  "MPEG-4",
  "MSF",
  "Musepack",
  "Musepack SV8",
  "Material eXchange Format (MXF)",
  "Material eXchange Format (MXF), D-10 Mapping",
  "NC camera feed",
  "NIST SPeech HEader REsources",
  "Computerized Speech Lab NSP",
  "NTT TwinVQ (VQF)",
  "Nullsoft Streaming Video",
  "NuppelVideo",
  "NUT",
  "Ogg",
  "Playstation Portable PMP",
  "Portable Voice Format",
  "RK Audio (RKA)",
  "TechnoTrend PVA",
  "QCP",
  "raw ADTS (AAC)",
  "raw AC-3",
  "raw AMR-NB",
  "raw AMR-WB",
  "raw APAC",
  "raw aptX",
  "raw aptX HD",
  "raw Bonk",
  "raw Chinese AVS video",
  "raw DFPWM",
  "raw Dirac",
  "raw DNxHD",
  "raw DTS",
  "raw DTS-HD",
  "raw E-AC-3",
  "raw EVC",
  "raw FLAC",
  "raw GSM",
  "raw H.261",
  "raw H.263",
  "raw H.264",
  "raw HEVC",
  "raw Ingenient MJPEG",
  "raw MJPEG",
  "raw MLP",
  "raw MPEG",
  "raw MPEG-1",
  "raw MPEG-2",
  "raw MPEG-4",
  "raw NULL",
  "raw video",
  "raw id RoQ",
  "raw OBU",
  "raw OSQ",
  "raw SBC",
  "raw Shorten",
  "raw TAK",
  "raw TrueHD",
  "raw VC-1",
  "raw PCM A-law",
  "raw PCM mu-law",
  "raw PCM Archimedes VIDC",
  "raw PCM signed 8 bit",
  "raw PCM signed 16 bit big-endian",
  "raw PCM signed 16 bit little-endian",
  "raw PCM signed 24 bit big-endian",
  "raw PCM signed 24 bit little-endian",
  "raw PCM signed 32 bit big-endian",
  "raw PCM signed 32 bit little-endian",
  "raw PCM signed 64 bit big-endian",
  "raw PCM signed 64 bit little-endian",
  "raw PCM unsigned 8 bit",
  "raw PCM unsigned 16 bit big-endian",
  "raw PCM unsigned 16 bit little-endian",
  "raw PCM unsigned 24 bit big-endian",
  "raw PCM unsigned 24 bit little-endian",
  "raw PCM unsigned 32 bit big-endian",
  "raw PCM unsigned 32 bit little-endian",
  "raw PCM 16.8 floating point little-endian",
  "raw PCM 24.0 floating point little-endian",
  "raw PCM floating-point 32 bit big-endian",
  "raw PCM floating-point 32 bit little-endian",
  "raw PCM floating-point 64 bit big-endian",
  "raw PCM floating-point 64 bit little-endian",
  "RDT",
  "REDCODE R3D",
  "RealMedia",
  "Redirector",
  "RedSpark",
  "Renderware TeXture Dictionary",
  "Resolume DXV",
  "RF64",
  "RL2",
  "RPL/ARMovie",
  "Lego Mindstorms RSO",
  "RSD",
  "RTMP",
  "RTP",
  "RTSP",
  "Sample Dump eXchange",
  "SAP",
  "SBG",
  "SDNS",
  "SDP",
  "SER",
  "Digital Pictures SGA",
  "Sega FILM/CPK",
  "Silicon Graphics Movie",
  "Sierra SOL",
  "Sierra VMD",
  "Smacker",
  "SMJPEG",
  "SMPTE 337M encapsulation",
  "Smush",
  "Sony OpenMG (OMA)",
  "Sony PlayStation STR",
  "Sony Wave64 (W64)",
  "SoX native format",
  "SUN AU format",
  "SUP raw PGS subtitles",
  "SVAG",
  "TDSC",
  "Text files",
  "THP",
  "Tiertex Limited SEQ",
  "True Audio",
  "VAG",
  "VC-1 test bitstream",
  "Vidvox Hap",
  "Vivo",
  "VPK",
  "Marble WADY",
  "WAV",
  "Waveform Archiver",
  "WavPack",
  "WebM",
  "Windows Televison (WTV)",
  "Wing Commander III movie",
  "Westwood Studios audio",
  "Westwood Studios VQA",
  "Wideband Single-bit Data (WSD)",
  "WVE",
  "Konami XMD",
  "XMV",
  "XVAG",
  "xWMA",
  "eXtended BINary text (XBIN)",
  "YUV4MPEG pipe",
  "Psygnosis YOP",
];

export const ffmpegImageFormats = [
  ".Y.U.V",
  "Alias PIX",
  "animated GIF",
  "APNG",
  "BMP",
  "BRender PIX",
  "CRI",
  "DPX",
  "EXR",
  "FITS",
  "HDR",
  "IMG",
  "JPEG",
  "JPEG 2000",
  "JPEG-LS",
  "LJPEG",
  "Media 100",
  "MSP",
  "PAM",
  "PBM",
  "PCD",
  "PCX",
  "PFM",
  "PGM",
  "PGMYUV",
  "PGX",
  "PHM",
  "PIC",
  "PNG",
  "PPM",
  "PSD",
  "PTX",
  "QOI",
  "SGI",
  "Sun Rasterfile",
  "TIFF",
  "Truevision Targa",
  "VBN",
  "WBMP",
  "WebP",
  "XBM",
  "XFace",
  "XPM",
  "XWD",
];

export const ffmpegVideoCodecs = [
  "MJPEG (Motion JPEG)",
  "Mobotix MxPEG video",
  "Motion Pixels video",
  "MPEG-1 video",
  "MPEG-2 video",
  "MPEG-4 part 2",
  "MPEG-4 part 2 Microsoft variant version 1",
  "MPEG-4 part 2 Microsoft variant version 2",
  "MPEG-4 part 2 Microsoft variant version 3",
  "Newtek SpeedHQ",
  "Nintendo Gamecube THP video",
  "NotchLC",
  "NuppelVideo/RTjpeg",
  "On2 VP3",
  "On2 VP4",
  "On2 VP5",
  "On2 VP6",
  "On2 VP7",
  "VP8",
  "VP9",
  "Pinnacle TARGA CineWave YUV16",
  "Q-team QPEG",
  "QuickTime 8BPS video",
  "QuickTime Animation (RLE) video",
  "QuickTime Graphics (SMC)",
  "QuickTime video (RPZA)",
  "R10K AJA Kona 10-bit RGB Codec",
  "R210 Quicktime Uncompressed RGB 10-bit",
  "Raw Video",
  "RealVideo 1.0",
  "RealVideo 2.0",
  "RealVideo 3.0",
  "RealVideo 4.0",
  "RealVideo 6.0",
  "Renderware TXD (TeXture Dictionary)",
  "RivaTuner Video",
  "RL2 video",
  "RPL/ARMovie",
  "Lego Mindstorms RSO",
  "RSD",
  "RTMP",
  "RTP",
  "RTSP",
  "Sample Dump eXchange",
  "SAP",
  "SBG",
  "SDNS",
  "SDP",
  "SER",
  "Digital Pictures SGA",
  "Sega FILM/CPK",
  "Silicon Graphics Movie",
  "Sierra SOL",
  "Sierra VMD video",
  "Smacker video",
  "SMJPEG",
  "SMPTE 337M encapsulation",
  "Smush",
  "Sony OpenMG (OMA)",
  "Sony PlayStation STR",
  "Sony Wave64 (W64)",
  "SoX native format",
  "SUN AU format",
  "SUP raw PGS subtitles",
  "SVAG",
  "TDSC",
  "Text files",
  "THP",
  "Tiertex Limited SEQ",
  "True Audio",
  "VAG",
  "VC-1 test bitstream",
  "Vidvox Hap",
  "Vivo",
  "VPK",
  "Marble WADY",
  "WAV",
  "Waveform Archiver",
  "WavPack",
  "WebM",
  "Windows Televison (WTV)",
  "Wing Commander III movie",
  "Westwood Studios audio",
  "Westwood Studios VQA",
  "Wideband Single-bit Data (WSD)",
  "WVE",
  "Konami XMD",
  "XMV",
  "XVAG",
  "xWMA",
  "eXtended BINary text (XBIN)",
  "YUV4MPEG pipe",
  "Psygnosis YOP",
];

export const ffmpegAudioCodecs = [
  "8SVX exponential",
  "8SVX fibonacci",
  "AAC",
  "AAC+",
  "AC-3",
  "ACELP.KELVIN",
  "ADPCM 4X Movie",
  "ADPCM Yamaha AICA",
  "ADPCM AmuseGraphics Movie",
  "ADPCM Argonaut Games",
  "ADPCM CDROM XA",
  "ADPCM Creative Technology",
  "ADPCM Electronic Arts",
  "ADPCM Electronic Arts Maxis CDROM XS",
  "ADPCM Electronic Arts R1",
  "ADPCM Electronic Arts R2",
  "ADPCM Electronic Arts R3",
  "ADPCM Electronic Arts XAS",
  "ADPCM G.722",
  "ADPCM G.726",
  "ADPCM IMA Acorn Replay",
  "ADPCM IMA AMV",
  "ADPCM IMA Cunning Developments",
  "ADPCM IMA Electronic Arts EACS",
  "ADPCM IMA Electronic Arts SEAD",
  "ADPCM IMA Funcom",
  "ADPCM IMA High Voltage Software ALP",
  "ADPCM IMA Mobiclip MOFLEX",
  "ADPCM IMA QuickTime",
  "ADPCM IMA Simon & Schuster Interactive",
  "ADPCM IMA Ubisoft APM",
  "ADPCM IMA Loki SDL MJPEG",
  "ADPCM IMA WAV",
  "ADPCM IMA Westwood",
  "ADPCM ISS IMA",
  "ADPCM IMA Dialogic",
  "ADPCM IMA Duck DK3",
  "ADPCM IMA Duck DK4",
  "ADPCM IMA Radical",
  "ADPCM IMA Xbox",
  "ADPCM Microsoft",
  "ADPCM MS IMA",
  "ADPCM Nintendo Gamecube AFC",
  "ADPCM Nintendo Gamecube DTK",
  "ADPCM Nintendo THP",
  "ADPCM Playstation",
  "ADPCM QT IMA",
  "ADPCM SEGA CRI ADX",
  "ADPCM Shockwave Flash",
  "ADPCM Sound Blaster Pro 2-bit",
  "ADPCM Sound Blaster Pro 2.6-bit",
  "ADPCM Sound Blaster Pro 4-bit",
  "ADPCM VIMA",
  "ADPCM Konami XMD",
  "ADPCM Westwood Studios IMA",
  "ADPCM Yamaha",
  "ADPCM Zork",
  "AMR-NB",
  "AMR-WB",
  "Amazing Studio PAF Audio",
  "Apple lossless audio",
  "aptX",
  "aptX HD",
  "ATRAC1",
  "ATRAC3",
  "ATRAC3+",
  "ATRAC9",
  "Bink Audio",
  "Bonk audio",
  "CELT",
  "codec2",
  "CRI HCA",
  "Delphine Software International CIN audio",
  "DFPWM",
  "Digital Speech Standard - Standard Play mode (DSS SP)",
  "Discworld II BMV Audio",
  "COOK",
  "DCA (DTS Coherent Acoustics)",
  "Dolby E",
  "DPCM Cuberoot-Delta-Exact",
  "DPCM Gremlin",
  "DPCM id RoQ",
  "DPCM Marble WADY",
  "DPCM Interplay",
  "DPCM Squareroot-Delta-Exact",
  "DPCM Sierra Online",
  "DPCM Sol",
  "DPCM Xan",
  "DPCM Xilam DERF",
  "DSD (Direct Stream Digital), least significant bit first",
  "DSD (Direct Stream Digital), most significant bit first",
  "DSD (Direct Stream Digital), least significant bit first, planar",
  "DSD (Direct Stream Digital), most significant bit first, planar",
  "DSP Group TrueSpeech",
  "DST (Direct Stream Transfer)",
  "DV audio",
  "Enhanced AC-3",
  "EVRC (Enhanced Variable Rate Codec)",
  "FLAC (Free Lossless Audio Codec)",
  "FTR Voice",
  "G.723.1",
  "G.729",
  "GSM",
  "GSM Microsoft variant",
  "IAC (Indeo Audio Coder)",
  "iLBC (Internet Low Bitrate Codec)",
  "IMC (Intel Music Coder)",
  "Interplay ACM",
  "LC3",
  "MACE (Macintosh Audio Compression/Expansion) 6:1",
  "Marian’s A-pac audio",
  "MI-SC4 (Micronas SC-4 Audio)",
  "MLP (Meridian Lossless Packing)",
  "Monkey’s Audio",
  "MP1 (MPEG audio layer 1)",
  "MP2 (MPEG audio layer 2)",
  "MP3 (MPEG audio layer 3)",
  "MPEG-4 Audio Lossless Coding (ALS)",
  "MobiClip FastAudio",
  "Musepack SV7",
  "Musepack SV8",
  "Nellymoser Asao",
  "On2 AVC (Audio for Video Codec)",
  "Opus",
  "OSQ (Original Sound Quality)",
  "PCM A-law",
  "PCM mu-law",
  "PCM Archimedes VIDC",
  "PCM signed 8-bit planar",
  "PCM signed 16-bit big-endian planar",
  "PCM signed 16-bit little-endian planar",
  "PCM signed 24-bit little-endian planar",
  "PCM signed 32-bit little-endian planar",
  "PCM 32-bit floating point big-endian",
  "PCM 32-bit floating point little-endian",
  "PCM 64-bit floating point big-endian",
  "PCM 64-bit floating point little-endian",
  "PCM D-Cinema audio signed 24-bit",
  "PCM signed 8-bit",
  "PCM signed 16-bit big-endian",
  "PCM signed 16-bit little-endian",
  "PCM signed 24-bit big-endian",
  "PCM signed 24-bit little-endian",
  "PCM signed 32-bit big-endian",
  "PCM signed 32-bit little-endian",
  "PCM 16/20/24-bit big-endian in MPEG-TS",
  "PCM unsigned 8-bit",
  "PCM unsigned 16-bit big-endian",
  "PCM unsigned 16-bit little-endian",
  "PCM unsigned 24-bit big-endian",
  "PCM unsigned 24-bit little-endian",
  "PCM unsigned 32-bit big-endian",
  "PCM unsigned 32-bit little-endian",
  "PCM SGA",
  "QCELP / PureVoice",
  "QDesign Music Codec 1",
  "QDesign Music Codec 2",
  "RealAudio 1.0 (14.4K)",
  "RealAudio 2.0 (28.8K)",
  "RealAudio 3.0 (dnet)",
  "RealAudio Lossless",
  "RealAudio SIPR / ACELP.NET",
  "RK Audio (RKA)",
  "SBC (low-complexity subband codec)",
  "Shorten",
  "Sierra VMD audio",
  "Smacker audio",
  "SMPTE 302M AES3 audio",
  "Sonic",
  "Sonic lossless",
  "Speex",
  "TAK (Tom’s lossless Audio Kompressor)",
  "True Audio (TTA)",
  "TrueHD",
  "TwinVQ (VQF flavor)",
  "VIMA",
  "ViewQuest VQC",
  "Vorbis",
  "Voxware MetaSound",
  "Waveform Archiver",
  "WavPack",
  "Westwood Audio (SND1)",
  "Windows Media Audio 1",
  "Windows Media Audio 2",
  "Windows Media Audio Lossless",
  "Windows Media Audio Pro",
  "Windows Media Audio Voice",
  "Xbox Media Audio 1",
  "Xbox Media Audio 2",
];

export const ffmpegSubtitleFormats = [
  "3GPP Timed Text",
  "AQTitle",
  "DVB",
  "DVB teletext",
  "DVD",
  "JACOsub",
  "MicroDVD",
  "MPL2",
  "MPsub (MPlayer)",
  "PGS",
  "PJS (Phoenix)",
  "RealText",
  "SAMI",
  "Spruce format (STL)",
  "SSA/ASS",
  "SubRip (SRT)",
  "SubViewer v1",
  "SubViewer",
  "TED Talks captions",
  "TTML",
  "VobSub (IDX+SUB)",
  "VPlayer",
  "WebVTT",
  "XSUB",
];

export const ffmpegNetworkProtocols = [
  "AMQP",
  "file",
  "FTP",
  "Gopher",
  "Gophers",
  "HLS",
  "HTTP",
  "HTTPS",
  "Icecast",
  "MMSH",
  "MMST",
  "pipe",
  "Pro-MPEG FEC",
  "RTMP",
  "RTMPE",
  "RTMPS",
  "RTMPT",
  "RTMPTE",
  "RTMPTS",
  "RTP",
  "SAMBA",
  "SCTP",
  "SFTP",
  "TCP",
  "TLS",
  "UDP",
  "ZMQ",
];

export const ffmpegInputOutputDevices = [
  "ALSA",
  "BKTR",
  "caca",
  "DV1394",
  "Lavfi virtual device",
  "Linux framebuffer",
  "JACK",
  "LIBCDIO",
  "LIBDC1394",
  "OpenAL",
  "OpenGL",
  "OSS",
  "PulseAudio",
  "SDL",
  "Video4Linux2",
  "VfW capture",
  "X11 grabbing",
  "Win32 grabbing",
];

export const ffmpegTimecode = [
  "AVI",
  "DV",
  "GXF",
  "MOV",
  "MPEG1/2",
  "MXF",
];